project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    include-highlights-only: true
    theme: default
    css: styles.css
  pdf:
    include-highlights-only: false
    pdf-engine: xelatex
    documentclass: article
    toc: false

website:
  title: "Ben Coombs – CV"
  navbar:
    left:
      - text: "CV"
        href: cv.html
